spring.application.name=cronex-api
server.port=8081

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# PROFILE
spring.profiles.active = ${SPRING_PROFILES_ACTIVE}

spring.flyway.enabled=true

spring.web.resources.add-mappings=false

spring.security.token.secret=${JWT_SECRET_KEY}