spring.application.name=cronex-api
server.port=8081

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# PROFILE
spring.profiles.active = ${SPRING_PROFILES_ACTIVE}

spring.flyway.enabled=true